### ISSUE TITLE
Changing width of the right valuegrid has some interesting behaviour

### ISSUE THREAD

**Issue by phecdaDia** [valarnin/NTRRemoteDebugger#1]
Changing the width of the columns of the lower right valuesgrid has an interesting behaviour. It seems to be irreversable.  

Steps:  
- Connect to the 3ds
- select a process
- find any value
- select the value
- change the width of the column

Todo:
Fix the width of the columns

**Comment by valarnin** [comment]
Fixed in commit 3ec1f523c6031050065789b4d06bbbeae6ac36f4.
