### ISSUE TITLE
Support for saving the address list to a file

### ISSUE THREAD

**Issue by aldelaro5** [valarnin/NTRRemoteDebugger#14]
Adding such a feature would allow the user to save in a file the address list from the right table.  This will allow to add the convenience of being able to preserve multiple addresses somewhere and when this file would be opened, it could add all addresses from the file in the right table.  It would be meant to preserve known addresses without having to add them manually when needed.

Something like XML format could work due to the simplicity of the data to save so far (it would just be the address and its type for now, but it also allows to add data easily if it were to become useful).  Implementing this feature shouldn't take much since it is mostly a matter of parsing the data which already exists somewhere.

**Comment by phecdaDia** [comment]
I'll take care about this.

**Comment by phecdaDia** [comment]
Added this to my current fork, waiting for PR.  
Valarnin will probably adjust some stuff after the PR and it should be included in the next release.

**Comment by phecdaDia** [comment]
See pull request #15
