### ISSUE TITLE
Decreased, increased, increased by and decreased by search types are innacurate / broken

### ISSUE THREAD

**Issue by aldelaro5** [valarnin/NTRRemoteDebugger#16]
I had some doubts so I did more serious tests with the HP address in Paper Mario Sticker Star (the address is 082BCEA0 , put 2 or 4 bytes as type as they both work).

I selected a custom range to start at 082BCE00 and be of size 100 so that way, I get quick scans with the address I know in it.  I searched for unknown 2 byte and I made sure that 082BCEA0 was in the found list each time.

What I would do is decrease or increase the value in game and made the appropriate second search.

The results I got was that decreased and increased go through, but the address isn't found while the value did increased/decreased.  As for increased by and decreased by, they simply made the program crash with this exception:

> An unhandled exception of type 'System.ArgumentException' occurred in mscorlib.dll
> 
> Additional information: Destination array is not long enough to copy all the items in the collection. Check array index and length.

I got similar results before with a float value that I knew its variations.

On a side note, decreased and increased do nothing if the value text box is cleared, I had to put something like 0 which shouldn’t happen.

**Comment by valarnin** [comment]
These were functional for 4 byte last I checked, I'm not sure when they broke. Not sure when I'd be able to investigate but I'd probably just try searching for character X/Y/Z position in FFEX as I have a good way to determine where the character struct is in memory for it. That'll let me knock out both float/double and increased/decreased at the same time.

**Comment by aldelaro5** [comment]
Well, actually, I was trying to search coordinates from Sticker Star and this is how I had doubts with increased/decreased because the scans didn't made sense until I tried different/same which did worked (and luckily, it narrowed it down enough so that I had an idea of the Z position when I was hugging a wall in a certain map so I could narrow it down further).

If it helps, I got that doubt on 8.5.

**Comment by valarnin** [comment]
Increased/Decreased are reversed in the code (whoops). Increased By/Decreased By only work for Integers currently at a glance at the code, I'm not sure if they're working properly yet, testing now.

**Comment by valarnin** [comment]
Increased By/Decreased By were also reversed in the code and I have fixed all 4 options locally as far as being reversed. I'm still investigating how to fix the By options to work with other data types. May be a difficult problem to fix due to the nature of floating point numbers.
To clarify, the By options work for 1/2/4/8 bytes currently. Technically they should also work for Float/Double but they round the difference to the nearest whole number before checking against the input value (which is also rounded to the nearest whole number).
