### ISSUE TITLE
'Reset' button not removing values from memory when changing to a different datatype.

### ISSUE THREAD

**Issue by phecdaDia** [valarnin/NTRRemoteDebugger#2]
When having a large amount of values ( about 100 or so ) when changing the datatype and pressing reset to do a new search the old values are still in memory. You have to press 'Reset' twice

Steps:
- Connect to the 3ds
- Open a process
- Find many values of the type A ( this can be anything, 2 Bytes, 4 Bytes.. etc )
  . Press 'Reset'
- Change the datatype
- Search for any other value

Todo:
No idea.

**Comment by valarnin** [comment]
Fixed in commit 529fac0
