### ISSUE TITLE
Raw Memory Data Viewer

### ISSUE THREAD

**Issue by valarnin** [valarnin/NTRRemoteDebugger#7]
Add the ability to right click an address and get the previous and next 1024 bytes around that address to be viewed (total bytes read from 3DS = 2048+Data Type Size). Then display in some sort of viewer, with the ability to add addresses from the viewer as values to be modified.

**Comment by f-israel** [comment]
guess you can take the changes in pull request as base idea. tried to increase the memory range but reading time gets beyond good user experience. guess it's a good time-data compromise to stay with (address+/-512 bytes) range.

**Comment by valarnin** [comment]
The viewer should probably be able to modify displayed data as well. Closed #21 in favor of this issue.

**Comment by f-israel** [comment]
Modifing data was implemented shortly after my post. In commit c3d1b7e7c15a6fb4a4f11d23e8aa3b17cbc6c82e

**Comment by valarnin** [comment]
Merged to master in PR #24
