### ISSUE TITLE
List empty / Configurable amount of search results to display

### ISSUE THREAD

**Issue by NathanDreamweaver** [valarnin/NTRRemoteDebugger#9]
Hi! Everytime i schearc for a value it says tha he found a lot of result but the list is empty!

**Comment by phecdaDia** [comment]
If there are more then 50 entrys I think it won't show them.

**Comment by valarnin** [comment]
That's correct, it only shows 50 entries top right now. I'm going to be adding a config file or something to an upcoming version where you can change that, but I haven't had time to work on this and haven't been able to get NTRCFW to work on 10.6 emunand either.

**Comment by NathanDreamweaver** [comment]
i have a 10.6 emunand and using ntr cfw modded by Shadowtrance

**Comment by valarnin** [comment]
I'm going to go ahead and change this to a feature request for being able to configure the amount of search results to display.

**Comment by valarnin** [comment]
Implemented in v0.8.1.0.
